In [ ]:
#Question1

import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [ ]:
#Question 3 

import numpy as np
# Creating array object
arr = np.array( [[ 1, 2, 3],[ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [ ]:
#Question 2

import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)
#array([[1, 2],[3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Question 4

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
# Modify the 2D numpy array (View object)
arr_2d[0][0] = 22
print('1D Numpy array:')
print(arr)
print('2D Numpy array:')
print(arr_2d)

1D Numpy array:
[22  1  2  3  4  5  6  7  8  9]
2D Numpy array:
[[22  1  2  3  4]
 [ 5  6  7  8  9]]


In [ ]:
#Question 5

## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])
i = np.array([7,8,9])
print('Vertical Append: \n ' , np.vstack((f, g,i)))

Vertical Append: 
  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Question 6

a_list = [1, 2, 3 ,4, 5]
a_set = set(a_list)
number_of_unique_values = len(a_set)
print(number_of_unique_values)

5
